name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. تنزيل الكود
      - uses: actions/checkout@v4

      # 2. تثبيت جافا المطلوبة لبناء أندرويد
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. تثبيت Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. توليد ملفات بيئة أندرويد تلقائياً
      - run: flutter create . --platforms=android

      # 5. جلب المكتبات
      - run: flutter pub get

      # 6. بناء ملف الـ APK
      - run: flutter build apk --release

      # 7. رفع ملف الـ APK للتحميل
      - uses: actions/upload-artifact@v4
        with:
          name: InfraPricing-App
          path: build/app/outputs/flutter-apk/app-release.apk
